version: "3.3"

services:
  my-server:
    build:
      context: ./server
    restart: always
    environment:
      VIRTUAL_HOST: lager-simulator-2023.lo
      # LETSENCRYPT_HOST: # TODO Choose domain: lager-simulator.georgs-punkte.de (?)
      # LETSENCRYPT_EMAIL: vincent.mader@icloud.com
    ports:
      - 5001:5000
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: proxy_my_awesome_proxy_network # same name as in `./proxy/docker-compose.yml` + prefix (see "docker network ls")
