version: "3.3"

services:
  my-server:
    build:
      context: ./server
    restart: always
    environment:
      VIRTUAL_HOST: lager-simulator.georgs-punkte.de, lager-simulator-2023.lo
      LETSENCRYPT_HOST: lager-simulator.georgs-punkte.de
      LETSENCRYPT_EMAIL: vincent.mader@icloud.com
    ports:
      - 5011:5000
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in `./proxy/docker-compose.yml`.
    #   Additionally, it it prefixed by the proxy directory name (see "docker network ls").
